### ISSUE TITLE
Cinnamon trees never spawn

### ISSUE THREAD

**Issue by tungstonminer** [ferreusveritas/DynamicTrees-PHC#11]
# Setup

* Minecraft v1.12.2
* Forge v14.23.5.2854
* HarvestCraft v1.12.2.zg
* Nature's Compass v1.8.5

# Steps

1. Create a profile and install the indicated mods using the Curseforge / Overwolf launcher
2. Alter `harvestcraft_fruittree.cfg` to disable all trees *except* the cinnamon tree
3. Create a new world, and use the Nature's Compass to teleport to a savanna biome
4. Fly about for a bit.  Note that you will see many vanilla-style cinnamon trees
5. Quit the game, and add the following mods to the pack:
  * Dynamic Trees v0.9.22
  * Dynamic Trees PHC v2.0.5
6. Change the `dynamictreesphc.cfg` to set `S:fruitTreeOccurance` to 1.0
6. Create a fresh new world, and use Nature's Compass to teleport to a savanna biome
7. Fly about for a bit.  Note that no cinnamon trees appear.

# CurseForge Modpack

If you prefer, this is the CurseForge/Overwolf modpack in its entirety:

[cinnamon-test-0.0.1.zip](https://github.com/ferreusveritas/DynamicTrees-PHC/files/6209149/cinnamon-test-0.0.1.zip)

**Comment by tungstonminer** [comment]
I haven't re-created the test for it, but I suspect the same may be true for maple trees.  I've spent quite some time looking for one in my modpack worlds with no luck finding any.

**Comment by tungstonminer** [comment]
Yup, just confirmed.  If you have the `S:fruitTreeOccurance` to `1.0` with the `minecraft:taiga` biome in the whitelist, I would expect *all* trees to be replaced with spruce trees, but actually *none* are.

**Comment by supermassimo** [comment]
Will definitely take a look, thanks for the thorough investigation!
