### ISSUE TITLE
No cinnamon trees in the world.

### ISSUE THREAD

**Issue by ghost** [ferreusveritas/DynamicTrees-PHC#15]
For a very long time I flew over the biomes of the jungle and swamps, and also increased the frequency of the appearance of cinnamon trees, but these trees never spawned.

**Comment by ghost** [comment]
debug.log says:
`[Client thread/INFO] [STDERR]: [com.ferreusveritas.dynamictrees.util.Deprecatron:Complain:17]: The Block version of addAcceptableSoil is DEPRECATED. Species: dynamictreesphc:cinnamon`

**Comment by supermassimo** [comment]
What version is this?

**Comment by ghost** [comment]
DynamicTreesPHC-1.12.2-2.0.6.jar

**Comment by supermassimo** [comment]
Have you found paperbark or maple trees? Or is cinnamon the only one missing

**Comment by ghost** [comment]
I did not find paperbark and maple in the world. Even after I set `I:rarity=0` for each of them in the config.

**Comment by supermassimo** [comment]
Seems like the generators for non-fruit trees is missing, unfortunately we no longer support the 1.12 versions of our mods so there's not much I can do to help here
