### ISSUE TITLE
Fruit Bearing Trees don't drop respective fruit tree sapling

### ISSUE THREAD

**Issue by SiggiVG** [ferreusveritas/DynamicTrees-PHC#4]
Fruit and other trees added by Pam's Harvestcraft are not dropping their respective fruit tree seeds, just the seeds of the leaf type they use (such as oak).

**Comment by ghost** [comment]
Maple, Paperbark and Cinnamon should be the only seeds that are dropped from the leaves. I acknowledge that this feature is indeed broken.
For the other fruit seeds the dirt bucket + fruit exchange recipe is the official method.
