### ISSUE TITLE
Maple trees do not drop any wood

### ISSUE THREAD

**Issue by SiggiVG** [ferreusveritas/DynamicTrees-PHC#5]
Mable trees do not drop Pam's Harvestcraft Maple wood, or any wood. The only drops are maple syrup (and the seeds from the leaves).

**Comment by ghost** [comment]
Does Pam's Harvestcraft even have log blocks you can obtain normally?

**Comment by SiggiVG** [comment]
It has maple logs, which can be crafted into spruce planks.
