### ISSUE TITLE
Console spam on world gen.

### ISSUE THREAD

**Issue by Boymann** [ferreusveritas/DynamicTrees-PHC#7]
I can't seem to paste the log here, so here's a paste:
https://paste.ee/p/LfFoD#bcP0owEAb1HmWKhBK1v3VCfTHgTWQga7

**Comment by kierajreed** [comment]
Can you reproduce this with only Dynamic Trees? And then with DT, PHC, and this addon?

**Comment by Boymann** [comment]
I tried for about 20 minutes with only DT,DT-PHC,DT-BOP, BOP and PHC. Got nothing.

**Comment by kierajreed** [comment]
Therefore, it is an intermod conflict and those are ignored unless specifically identified and traced by a third party. Sorry.

**Comment by Boymann** [comment]
I will try to trace it when I'll have time. Thank you for the response!
